services:
  postgres-db:
    image: postgres:15-alpine
    container_name: rastreador_postgres_local
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: rastreador_local
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: