spring.application.name=rastreador_backend
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/rastreador_local}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:root}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

//TODO: quitar la key
rapidapi.amazon-api.key = ${RAPIDAPI_KEY:tu-key-aqui}
rapidapi.amazon-api.host = ${RAPIDAPI_HOST:tu-host-aqui}