spring.application.name=rastreador_backend
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/rastreador_local}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:root}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


rapidapi.amazon-api.key = ${RAPIDAPI_KEY:16338621cemsh121a3c1b30352a4p1e4509jsn2f2a4cf1c629}
rapidapi.amazon-api.host = ${RAPIDAPI_HOST:real-time-amazon-data.p.rapidapi.com}

jwt.secretKey = ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
jwt.expiration = 86400000

spring.mail.host=${MAIL_HOST:sandbox.smtp.mailtrap.io}
spring.mail.port=${MAIL_PORT:2525}
spring.mail.username=${MAIL_USERNAME:ca6781bac18b65}
spring.mail.password=${MAIL_PASSWORD:03ea5738116476}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
app.mail.from=${MAIL_FROM:alertas@rastreador.com}